Repository Montaigne-ensaios/montaigne_app, pull requests merged in 2022-09, with the labels that each got.

#29 #22
  app/src/main/java/com/montaigne/montaigneapp/activity/AbstractActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/carimboDefinitivo/CarimboDefinitivoActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/home/HomeActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/carimboUnico/CarimboUnicoActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/ensaio/EnsaioActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/furo/FuroActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/projeto/ProjetoActivity.java
Labels: organization

#34 #28
  .idea/misc.xml
  app/src/main/java/com/montaigne/montaigneapp/activity/AbstractActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/carimboDefinitivo/CarimboDefinitivoVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/home/HomeVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/home/ProjetosSalvosAdapter.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/carimboUnico/CarimboUnicoVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/ensaio/EnsaioVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/projeto/ProjetoActivity.java
Labels: back-end, tweak

#36 #13
  .idea/misc.xml
  app/src/main/java/com/montaigne/montaigneapp/activity/carimboDefinitivo/CarimboDefinitivoActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/carimboDefinitivo/CarimboDefinitivoVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/home/HomeActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/home/HomeVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/carimboUnico/CarimboUnicoActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/carimboUnico/CarimboUnicoVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/ensaio/EnsaioActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/ensaio/EnsaioVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/furo/FuroActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/furo/FuroVM.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/projeto/ProjetoActivity.java
  app/src/main/java/com/montaigne/montaigneapp/activity/spt/projeto/ProjetoVM.java
Labels: front-end, organization
